---
- name: Deploy DevOps Mission Control App
  hosts: new_servers
  become: yes
  tasks:
    - name: Update apt and install Docker & Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Clone the project repository
      git:
        repo: https://github.com/maghakyanyuro-web/devops-end-to-end-project
        dest: /home/ubuntu/app
        force: yes

    - name: Start the Application using Docker Compose
      shell: |
        cd /home/ubuntu/app
        docker-compose up -d

