name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/devops-end-to-end-project
            git pull origin main
            docker image prune -f
            docker compose up --build -d
            HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:5000/api/info)
            if [ "$HTTP_STATUS" -eq 200]; then
              echo "Everything is fine👌✅"
            else
              echo "Deployment Failed❌ Backend returned status $HTTP_STATUS"
              docker compose logs backend
              exit 1
            fi
            docker compose ps
